<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EmployeeDetail;

class EmployeeDetailSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'user_id' => 5,
                'department_id' => 1,
                'position' => 'Software Developer',
                'salary' => 1000.00,
                'date_of_joining' => '2021-05-12',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 28,
                'date_of_birth' => '1996-03-15',
                'phone' => '+962799012345',
                'image' => 'employee_images/employee_5.jpg',
            ],
            [
                'user_id' => 6,
                'department_id' => 2,
                'position' => 'Network Engineer',
                'salary' => 1200.00,
                'date_of_joining' => '2019-08-01',
                'address' => 'Zarqa, Jordan',
                'nationality' => 'Jordan',
                'age' => 35,
                'date_of_birth' => '1989-02-20',
                'phone' => '+962781472346',
                'image' => 'employee_images/employee_6.jpg',
            ],
            [
                'user_id' => 7,
                'department_id' => 3,
                'position' => 'Data Analyst',
                'salary' => 800.00,
                'date_of_joining' => '2022-01-20',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 30,
                'date_of_birth' => '1993-07-10',
                'phone' => '+962788874347',
                'image' => 'employee_images/employee_7.jpg',
            ],
            [
                'user_id' => 8,
                'department_id' => 4,
                'position' => 'Support Technician',
                'salary' => 600.00,
                'date_of_joining' => '2020-03-15',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 42,
                'date_of_birth' => '1981-06-28',
                'phone' => '+962781157348',
                'image' => 'employee_images/employee_8.jpg',
            ],
            [
                'user_id' => 9,
                'department_id' => 5,
                'position' => 'Quality Assurance Tester',
                'salary' => 1000.00,
                'date_of_joining' => '2018-11-05',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 38,
                'date_of_birth' => '1985-04-12',
                'phone' => '+962789012349',
                'image' => 'employee_images/employee_9.jpg',
            ],
            [
                'user_id' => 10,
                'department_id' => 6,
                'position' => 'UX/UI Designer',
                'salary' => 1500.00,
                'date_of_joining' => '2019-04-10',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 32,
                'date_of_birth' => '1991-04-10',
                'phone' => '+962789054749',
                'image' => 'employee_images/employee_10.jpg',
            ],
            // Employee details for newly added users
            [
                'user_id' => 25,
                'department_id' => 1,
                'position' => 'Frontend Developer',
                'salary' => 1100.00,
                'date_of_joining' => '2020-06-15',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 29,
                'date_of_birth' => '1995-08-10',
                'phone' => '+962789123450',
                'image' => 'employee_images/employee_25.jpg',
            ],
            [
                'user_id' => 26,
                'department_id' => 2,
                'position' => 'Network Administrator',
                'salary' => 1300.00,
                'date_of_joining' => '2017-09-23',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 40,
                'date_of_birth' => '1983-01-12',
                'phone' => '+201001234567',
                'image' => 'employee_images/employee_26.jpg',
            ],
            [
                'user_id' => 27,
                'department_id' => 3,
                'position' => 'Business Intelligence Analyst',
                'salary' => 1250.00,
                'date_of_joining' => '2018-03-01',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 33,
                'date_of_birth' => '1990-04-18',
                'phone' => '+201002345678',
                'image' => 'employee_images/employee_27.jpg',
            ],
            [
                'user_id' => 28,
                'department_id' => 4,
                'position' => 'IT Support Specialist',
                'salary' => 900.00,
                'date_of_joining' => '2019-07-10',
                'address' => 'Zarqa, Jordan',
                'nationality' => 'Jordan',
                'age' => 38,
                'date_of_birth' => '1985-12-20',
                'phone' => '+962781234567',
                'image' => 'employee_images/employee_28.jpg',
            ],
            [
                'user_id' => 29,
                'department_id' => 5,
                'position' => 'QA Engineer',
                'salary' => 950.00,
                'date_of_joining' => '2021-10-05',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 35,
                'date_of_birth' => '1989-05-14',
                'phone' => '+962799876543',
                'image' => 'employee_images/employee_29.jpg',
            ],
            [
                'user_id' => 30,
                'department_id' => 6,
                'position' => 'Product Designer',
                'salary' => 1400.00,
                'date_of_joining' => '2020-08-01',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 28,
                'date_of_birth' => '1996-02-25',
                'phone' => '+962799567890',
                'image' => 'employee_images/employee_30.jpg',
            ],
            [
                'user_id' => 31,
                'department_id' => 1,
                'position' => 'DevOps Engineer',
                'salary' => 1500.00,
                'date_of_joining' => '2021-12-11',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 31,
                'date_of_birth' => '1992-09-08',
                'phone' => '+201011234567',
                'image' => 'employee_images/employee_31.jpg',
            ],
            [
                'user_id' => 32,
                'department_id' => 2,
                'position' => 'Network Security Specialist',
                'salary' => 1400.00,
                'date_of_joining' => '2016-05-15',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 45,
                'date_of_birth' => '1978-06-30',
                'phone' => '+962798765432',
                'image' => 'employee_images/employee_32.jpg',
            ],
            [
                'user_id' => 33,
                'department_id' => 3,
                'position' => 'Data Engineer',
                'salary' => 1250.00,
                'date_of_joining' => '2019-02-12',
                'address' => 'Zarqa, Jordan',
                'nationality' => 'Jordan',
                'age' => 37,
                'date_of_birth' => '1986-03-17',
                'phone' => '+962798765678',
                'image' => 'employee_images/employee_33.jpg',
            ],
            [
                'user_id' => 34,
                'department_id' => 4,
                'position' => 'Help Desk Technician',
                'salary' => 950.00,
                'date_of_joining' => '2020-11-03',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 29,
                'date_of_birth' => '1994-08-21',
                'phone' => '+201011234876',
                'image' => 'employee_images/employee_34.jpg',
            ],
            [
                'user_id' => 35,
                'department_id' => 5,
                'position' => 'Quality Assurance Analyst',
                'salary' => 1100.00,
                'date_of_joining' => '2021-01-08',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 27,
                'date_of_birth' => '1996-09-13',
                'phone' => '+962788765432',
                'image' => 'employee_images/employee_35.jpg',
            ],
            [
                'user_id' => 36,
                'department_id' => 1,
                'position' => 'Backend Developer',
                'salary' => 1300.00,
                'date_of_joining' => '2019-03-15',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 34,
                'date_of_birth' => '1989-05-07',
                'phone' => '+201011234567',
                'image' => 'employee_images/employee_36.jpg',
            ],
            [
                'user_id' => 37,
                'department_id' => 2,
                'position' => 'Wireless Network Engineer',
                'salary' => 1250.00,
                'date_of_joining' => '2018-06-22',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 38,
                'date_of_birth' => '1985-11-18',
                'phone' => '+201001122333',
                'image' => 'employee_images/employee_37.jpg',
            ],
            [
                'user_id' => 38,
                'department_id' => 3,
                'position' => 'Data Visualization Specialist',
                'salary' => 1100.00,
                'date_of_joining' => '2020-10-20',
                'address' => 'Zarqa, Jordan',
                'nationality' => 'Jordan',
                'age' => 32,
                'date_of_birth' => '1991-12-11',
                'phone' => '+962788765678',
                'image' => 'employee_images/employee_38.jpg',
            ],
            [
                'user_id' => 39,
                'department_id' => 6,
                'position' => 'Interaction Designer',
                'salary' => 1500.00,
                'date_of_joining' => '2019-08-04',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 29,
                'date_of_birth' => '1994-05-15',
                'phone' => '+962799012345',
                'image' => 'employee_images/employee_39.jpg',
            ],
            [
                'user_id' => 40,
                'department_id' => 4,
                'position' => 'Customer Support Specialist',
                'salary' => 1000.00,
                'date_of_joining' => '2021-04-10',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 40,
                'date_of_birth' => '1983-07-22',
                'phone' => '+962798765432',
                'image' => 'employee_images/employee_40.jpg',
            ],
            [
                'user_id' => 41,
                'department_id' => 5,
                'position' => 'Test Automation Engineer',
                'salary' => 1350.00,
                'date_of_joining' => '2017-02-18',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 35,
                'date_of_birth' => '1988-06-05',
                'phone' => '+201011234567',
                'image' => 'employee_images/employee_41.jpg',
            ],
            [
                'user_id' => 42,
                'department_id' => 1,
                'position' => 'Full Stack Developer',
                'salary' => 1450.00,
                'date_of_joining' => '2022-03-12',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 27,
                'date_of_birth' => '1995-07-30',
                'phone' => '+962788765678',
                'image' => 'employee_images/employee_42.jpg',
            ],
            [
                'user_id' => 43,
                'department_id' => 2,
                'position' => 'Network Architect',
                'salary' => 1600.00,
                'date_of_joining' => '2020-05-05',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 41,
                'date_of_birth' => '1982-08-25',
                'phone' => '+201001122333',
                'image' => 'employee_images/employee_43.jpg',
            ],
            [
                'user_id' => 44,
                'department_id' => 3,
                'position' => 'Data Scientist',
                'salary' => 1700.00,
                'date_of_joining' => '2021-11-01',
                'address' => 'Zarqa, Jordan',
                'nationality' => 'Jordan',
                'age' => 33,
                'date_of_birth' => '1990-04-10',
                'phone' => '+962799123456',
                'image' => 'employee_images/employee_44.jpg',
            ],
            [
                'user_id' => 45,
                'department_id' => 6,
                'position' => 'UX Designer',
                'salary' => 1400.00,
                'date_of_joining' => '2020-12-15',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 30,
                'date_of_birth' => '1993-09-22',
                'phone' => '+962788765678',
                'image' => 'employee_images/employee_45.jpg',
            ],
            [
                'user_id' => 46,
                'department_id' => 5,
                'position' => 'QA Manager',
                'salary' => 1600.00,
                'date_of_joining' => '2018-04-18',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 38,
                'date_of_birth' => '1985-11-14',
                'phone' => '+962799012345',
                'image' => 'employee_images/employee_46.jpg',
            ],
            [
                'user_id' => 47,
                'department_id' => 4,
                'position' => 'Technical Support Engineer',
                'salary' => 1200.00,
                'date_of_joining' => '2022-06-10',
                'address' => 'Cairo, Egypt',
                'nationality' => 'Egypt',
                'age' => 28,
                'date_of_birth' => '1995-03-05',
                'phone' => '+201011234567',
                'image' => 'employee_images/employee_47.jpg',
            ],
            [
                'user_id' => 48,
                'department_id' => 6,
                'position' => 'UI Designer',
                'salary' => 1350.00,
                'date_of_joining' => '2019-08-25',
                'address' => 'Alexandria, Egypt',
                'nationality' => 'Egypt',
                'age' => 32,
                'date_of_birth' => '1991-10-17',
                'phone' => '+201001122333',
                'image' => 'employee_images/employee_48.jpg',
            ],
            [
                'user_id' => 49,
                'department_id' => 1,
                'position' => 'Software Developer',
                'salary' => 1100.00,
                'date_of_joining' => '2020-09-09',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 29,
                'date_of_birth' => '1994-01-22',
                'phone' => '+962788765678',
                'image' => 'employee_images/employee_49.jpg',
            ],
            [
                'user_id' => 50,
                'department_id' => 2,
                'position' => 'Network Security Specialist',
                'salary' => 1300.00,
                'date_of_joining' => '2021-05-18',
                'address' => 'Irbid, Jordan',
                'nationality' => 'Jordan',
                'age' => 36,
                'date_of_birth' => '1987-08-30',
                'phone' => '+962799123456',
                'image' => 'employee_images/employee_50.jpg',
            ],
            [
                'user_id' => 51,
                'department_id' => 3,
                'position' => 'Data Engineer',
                'salary' => 1200.00,
                'date_of_joining' => '2022-01-15',
                'address' => 'Amman, Jordan',
                'nationality' => 'Jordan',
                'age' => 31,
                'date_of_birth' => '1992-11-11',
                'phone' => '+962788765678',
                'image' => 'employee_images/employee_51.jpg',
            ],
        ];

        foreach ($employees as $employee) {
            EmployeeDetail::create($employee);
        }
    }
}
